version: "3.8"

services:

  

  # Observability

  grafana:
    image: grafana/grafana:9.1.6
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./platform/grafana/dashboards:/etc/grafana/provisioning/dashboards

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./platform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"



