server:
  port: 8080

spring:
  application:
    name: gateway-marcadopago
  cloud:
    gateway:
      routes:
      - id: path_route_change
        uri: https://api.mercadopago.com/
        predicates:
        - Path=/mercado-pago/link-pagamento
        filters:
        - RewritePath=/mercado-pago/link-pagamento, /checkout/preferences
        - AddRequestHeader=Authorization, Bearer <TOKEN>
        - RequestBodyChange


